version: '3.1'
services:
  mongo_secondary_a:
    image:
      mongo
    command: --replSet rs0
    ports:
      - 27019:27017
    deploy:
      resources:
        limits:
          memory: 512M
  mongo_secondary_b:
    image:
      mongo
    command: --replSet rs0
    ports:
      - 27018:27017
    deploy:
      resources:
        limits:
          memory: 512M
  mongo:
    image:
      mongo
    command: --replSet rs0
    ports:
      - 27017:27017
    deploy:
      resources:
        limits:
          memory: 1G